/*****************************************************************************\
Copyright (C) 2017 Nyxxie <nyxxxxie@gmail.com>
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
Street, Fifth Floor, Boston, MA  02110-1301, USA.
\*****************************************************************************/

#ifndef HOTP_H
#define HOTP_H

#include <stdlib.h>
#include <stdint.h>

/* These determine the minimum and maximum amount of digits that can be safely
   generated by the HOTP function.  They are pulled directly from the RFC.  If
   you're at all concerned about the security of this algorithm, the RFC has a
   really nice section that talks in-depth about the security of HOTP. */
#define MIN_DIGITS 6
#define MAX_DIGITS 8

typedef struct hotp_digits {
    uint8_t digits[MAX_DIGITS];
    int digit_amt;
} hotp_digits;

int hotp(uint64_t counter, int digit_amt,
         const uint8_t* key, size_t key_len,
         hotp_digits* digits_out);

#endif /* HOTP_H */
